### ISSUE TITLE
[v3] Test watcher called with immediate option + ComponentGroup Discussion

### ISSUE THREAD

**Issue by silverbackdan** [components-web-app/cwa-nuxt-module#107]
It is important if we have used the `immediate` option or any options when calling methods that this is tested to harden our code.

We discussed the issue in testing the `watch` within the `ComponentGroup` as it is within the `setup` root level

To improve the readability and how well the code can be understood, it is agreed that the call to `watch` can be moved within a function which describes the watcher's function.

E.g. `synchroniseComponentGroup`

This watcher should only ever be fired on client-side and to prevent server-client mis-match we should move this into `onMounted` as it was before

In the case of this `ComponentGroup` vue component, I think I want to just check the logic of this as well. I perhaps hacked this in a bit fast.

We should also discuss the process in which this happens as well - being outside the `onMounted` could cause issues similar to the problem we had to resolve on `ResourceLoader`, where for a split second, the resource may not exist, but may end up existing.

The idea of this function is to create the component group data by calling the API if it does not exist, and to update the component group state to what has been defined in the layout/page if this has changed - and this only happens when a user is signed in.

**Comment by p1pchenk0** [comment]
PR is #108

**Comment by silverbackdan** [comment]
Thank you, please also see https://github.com/components-web-app/cwa-nuxt-module/tree/cg-sync-refactor and slack messages. I hadn't seen this before. Sorry

**Comment by silverbackdan** [comment]
Thank you, please also see https://github.com/components-web-app/cwa-nuxt-module/tree/cg-sync-refactor and slack messages. I hadn't seen this before. Sorry
