### ISSUE TITLE
[v3] Admin Component Manager

### ISSUE THREAD

**Issue by silverbackdan** [components-web-app/cwa-nuxt-module#124]
@p1pchenk0

- [x] All of the resource manager functions relating to clicking and adding to a stack should only occur when in `edit` mode which is already a state in the store. When `edit` mode is turned off, the resource stacks etc. should be cleared and no functionality should happen on click. It's probably best to isolate the blocking of functionality and clearing the resource stack into the CompoentManager class so we do not spread the logic out and there do not appear to be real overheads in the component registering a click.
- [x] Update tests now domElements is a reactive ref variable
- [x] Handle resource stack generation
- [x] Move event bus / emitter from cwa into `Admin` class, it makes sense to have an event bus relating to the services that we are emitting events for
- [x] We will need to emit an event when the stack is created for the item in the stack that should be selected. The purpose of the event is to inform all instances of this resource is should be highlighted, however we should also know if it was the instance of the resource that was clicked on. This is because there could be multiples of the same resource on a page and we will want to highlight differently.
- [x] We should add a dummy event listener for this event to highlight a resource on the screen
- [ ] NO LONGER REQUIRED _A component which has been added to a stack should be able to retrieve it's own state in the stack as well, this state will be extended to include information to link what is in the manager with the UI component itself. E.g. a toggle for showing or hiding an in-line HTML editor_
- [x] The admin component should also add an `onMounted` call to add a click event listener to the window and call `addToStack` so that a window click without anything else selected will clear the stack
- [x] ComponentManager should have a getter to return the current stack item
- [x] A component should be able to define it's own name in the stack using options when using a composable for `useCwaResource` or `useCwaResourceManageable`

**Comment by p1pchenk0** [comment]
this is for p.4: #125

**Comment by p1pchenk0** [comment]
for p.1 I've started #126, tell me if it is going in a right direction

**Comment by p1pchenk0** [comment]
for the last point do you mean something like this?
![image](https://github.com/components-web-app/cwa-nuxt-module/assets/7996276/e15713af-3cb2-499b-b1e3-ece5e0c57a33)
![image](https://github.com/components-web-app/cwa-nuxt-module/assets/7996276/41581525-0c54-43f1-a746-8361f2ad4288)

**Comment by silverbackdan** [comment]
For p1. I mean that the editMode we already have as a variable should be read in, and the stack empty or emptied when edit mode is false and addToStack not to add to stack, because we should only be able to click resources to edit when in edit mode.

**Comment by p1pchenk0** [comment]
> It's probably best to isolate the blocking of functionality and clearing the resource stack into the CompoentManager class so we do not spread the logic out and there do not appear to be real overheads in the component registering a click.

This is what I am doing by not allowing to add to stack and clearing stack within `ComponentManager` class as you mentioned in requirements

**Comment by silverbackdan** [comment]
Yes basically that, although I think in the options passed to useCwaResource, this should be an explicit option for the manager which then the entire manager options is passed to the nested composable. This will make passing options easier, defining the options as types easier and easier to extend options for any other nested composables we need in future.

**Comment by silverbackdan** [comment]
Sorry, for the edit mode, yes you are right :) I meant the `setEditMode` and local `isEditing` property is not needed, but instead we can get the edit mode from the admin store or the admin class getter directly.

**Comment by p1pchenk0** [comment]
do you mean passing `isEditing` getter from `Admin` class to `ComponentManager`? Because I've tried it and we get issue with pinia (we had such before, when pinia was used before created)

**Comment by silverbackdan** [comment]
I'm just saying we should not be replicating a boolean as a local variable is it's available globally

**Comment by p1pchenk0** [comment]
>The admin component should also add an onMounted call to add a click event listener to the window and call addToStack so that a window click without anything else selected will clear the stack

click listener can be easily added, however full implementation should wait till we have UI as we need to know which DOM elements belong to stack displaying/manipulation to not clear stack while clicking on those DOM elements

**Comment by silverbackdan** [comment]
>click listener can be easily added, however full implementation should wait till we have UI as we need to know which DOM elements belong to stack displaying/manipulation to not clear stack while clicking on those DOM elements

You've added this listener in your PR - this type of implementation is all good for now. No need for more.

**Comment by p1pchenk0** [comment]
p9 is in #127

**Comment by silverbackdan** [comment]
Thanks, merged

**Comment by silverbackdan** [comment]
We don't need to emit an event. The current stack item is watchable and public.
